package com.example.trainwatchrble.models.stations

enum class BlueStations(val led: Byte) {
    WONDERLAND_WEST(0),
    REVERE_BEACH_WEST(2),
    BEACHMONT_WEST(4),
    SUFFOLK_DOWNS_WEST(6),
    ORIENT_HEIGHTS_WEST(8),
    WOOD_ISLAND_WEST(10),
    AIRPORT_WEST(12),
    MAVERICK_WEST(14),
    AQUARIUM_WEST(16),
    STATE_WEST(18),
    GOVT_CENTER_WEST(20),
    BOWDOIN_WEST(22),


    WONDERLAND_EAST(23),
    REVERE_BEACH_EAST(25),
    BEACHMONT_EAST(27),
    SUFFOLK_DOWNS_EAST(29),
    ORIENT_HEIGHTS_EAST(31),
    WOOD_ISLAND_EAST(33),
    AIRPORT_EAST(35),
    MAVERICK_EAST(37),
    AQUARIUM_EAST(39),
    STATE_EAST(41),
    GOVT_CENTER_EAST(43),
    BOWDOIN_EAST(45),

}