package com.example.trainwatchrble.models.stations

enum class BlueStations(val led: Byte) {
    WONDERLAND_WEST(0),
    REVERE_BEACH_WEST(2),
    BEACHMONT_WEST(4),
    SUFFOLK_DOWNS_WEST(6),
    ORIENT_HEIGHTS_WEST(8),
    WOOD_ISLAND_WEST(10),
    AIRPORT_WEST(12),
    MAVERICK_WEST(14),
    AQUARIUM_WEST(17),
    STATE_WEST(19),
    GOVT_CENTER_WEST(21),
    BOWDOIN_WEST(23),


    WONDERLAND_EAST(24),
    REVERE_BEACH_EAST(26),
    BEACHMONT_EAST(28),
    SUFFOLK_DOWNS_EAST(30),
    ORIENT_HEIGHTS_EAST(32),
    WOOD_ISLAND_EAST(34),
    AIRPORT_EAST(36),
    MAVERICK_EAST(38),
    AQUARIUM_EAST(41),
    STATE_EAST(43),
    GOVT_CENTER_EAST(45),
    BOWDOIN_EAST(47),
}