package com.example.trainwatchrble.models.stations

enum class BlueStations(val led: Int) {
    WONDERLAND_EAST(0),
    REVERE_BEACH_EAST(2),
    BEACHMONT_EAST(4),
    SUFFOLK_DOWNS_EAST(6),
    ORIENT_HEIGHTS_EAST(8),
    WOOD_ISLAND_EAST(10),
    AIRPORT_EAST(12),
    MAVERICK_EAST(14),
    AQUARIUM_EAST(17),
    STATE_EAST(19),
    GOVT_CENTER_EAST(21),
    BOWDOIN_EAST(23),


    WONDERLAND_WEST(24),
    REVERE_BEACH_WEST(26),
    BEACHMONT_WEST(28),
    SUFFOLK_DOWNS_WEST(30),
    ORIENT_HEIGHTS_WEST(32),
    WOOD_ISLAND_WEST(34),
    AIRPORT_WEST(36),
    MAVERICK_WEST(38),
    AQUARIUM_WEST(41),
    STATE_WEST(43),
    GOVT_CENTER_WEST(45),
    BOWDOIN_WEST(47),
}