package com.example.trainwatchrble.models.stations

enum class RedStations(val led: Int) {
    ALEWIFE_SOUTH(0),
    DAVIS_SOUTH(2),
    PORTER_SOUTH(4),
    HARVARD_SOUTH(6),
    CENTRAL_SOUTH(8),
    KENDALL_MIT_SOUTH(10),
    CHARLES_MGH_SOUTH(12),
    PARK_STREET_SOUTH(14),
    DOWNTOWN_CROSSING_SOUTH(16),
    SOUTH_STATION_SOUTH(18),
    BROADWAY_SOUTH(21),
    ANDREW_SOUTH(23),
    JFK_UMASS_SAVIN_SOUTH(25),
    SAVIN_HILL_SOUTH(27),
    FIELDS_CORNER_SOUTH(29),
    SHAWMUT_SOUTH(31),
    ASHMONT_SOUTH(33),
    CEDAR_GROVE_SOUTH(35),
    BUTLER_SOUTH(37),
    MILTON_SOUTH(39),
    CENTRAL_AVE_SOUTH(41),
    VALLEY_ROAD_SOUTH(43),
    CAPEN_STREET_SOUTH(45),
    MATTAPAN_SOUTH(47),
    JFK_UMASS_NORTH_QUINCY_SOUTH(25),
    NORTH_QUINCY_SOUTH(49),
    WOLLASTON_SOUTH(51),
    QUINCY_CENTER_SOUTH(53),
    QUINCY_ADAMS_SOUTH(55),
    BRAINTREE_SOUTH(57),

    ALEWIFE_NORTH(58),
    DAVIS_NORTH(60),
    PORTER_NORTH(62),
    HARVARD_NORTH(64),
    CENTRAL_NORTH(66),
    KENDALL_MIT_NORTH(68),
    CHARLES_MGH_NORTH(70),
    PARK_STREET_NORTH(72),
    DOWNTOWN_CROSSING_NORTH(74),
    SOUTH_STATION_NORTH(76),
    BROADWAY_NORTH(79),
    ANDREW_NORTH(81),
    JFK_UMASS_SAVIN_NORTH(83),
    SAVIN_HILL_NORTH(85),
    FIELDS_CORNER_NORTH(87),
    SHAWMUT_NORTH(89),
    ASHMONT_NORTH(91),
    CEDAR_GROVE_NORTH(93),
    BUTLER_NORTH(95),
    MILTON_NORTH(97),
    CENTRAL_AVE_NORTH(99),
    VALLEY_ROAD_NORTH(101),
    CAPEN_STREET_NORTH(103),
    MATTAPAN_NORTH(105),
    JFK_UMASS_NORTH_QUINCY_NORTH(83),
    NORTH_QUINCY_NORTH(107),
    WOLLASTON_NORTH(109),
    QUINCY_CENTER_NORTH(111),
    QUINCY_ADAMS_NORTH(113),
    BRAINTREE_NORTH(115),
}

/*
0. &ALEWIFE_SOUTH
1. &ALEWIFE_TO_DAVIS
2. &DAVIS_SOUTH
3. &DAVIS_TO_PORTER
4. &PORTER_SOUTH
5. &PORTER_TO_HARVARD
6. &HARVARD_SOUTH
7. &HARVARD_TO_CENTRAL
8. &CENTRAL_SOUTH
9. &CENTRAL_TO_KENDALL
10. &KENDALL_SOUTH
11. &KENDALL_TO_CHARLES
12. &CHARLES_SOUTH
13. &CHARLES_TO_PARKRED
14. &PARKRED_SOUTH
15. &PARKRED_TO_DOWNTOWNRED
16. &DOWNTOWNRED_SOUTH
17. &DOWNTOWNRED_TO_SOUTH
18. &SOUTH_SOUTH
19. &SOUTH_TO_BROADWAY_1
20. &SOUTH_TO_BROADWAY_2
21. &BROADWAY_SOUTH
22. &BROADWAY_TO_ANDREW
23. &ANDREW_SOUTH
24. &ANDREW_TO_JFK
25. &JFK_SOUTH
26. &JFK_TO_SAVIN
27. &SAVIN_SOUTH
28. &SAVIN_TO_FIELDS
29. &FIELDS_SOUTH
30. &FIELDS_TO_SHAWMUT
31. &SHAWMUT_SOUTH
32. &SHAWMUT_TO_ASHMONT
33. &ASHMONT_SOUTH
34. &ASHMONT_TO_CEDAR_GROVE
35. &CEDAR_GROVE_SOUTH
36. &CEDAR_GROVE_TO_BUTLER
37. &BUTLER_SOUTH
38. &BUTLER_TO_MILTON
39. &MILTON_SOUTH
40. &MILTON_TO_CENTRALST
41. &CENTRALST_SOUTH
42. &CENTRAL_TO_VALLEY
43. &VALLEY_SOUTH
44. &VALLEY_TO_CAPEN
45. &CAPEN_SOUTH
46. &CAPEN_TO_MATTAPAN
47. &MATTAPAN_SOUTH
48. &JFK_TO_NQUINCY
49. &NQUINCY_SOUTH
50. &NQUINCY_TO_WOLLASTON
51. &WOLLASTON_SOUTH
52. &WOLLASTON_TO_CQUINCY
53. &QUINCYC_SOUTH
54. &QUINCYC_TO_QADAMS
55. &QADAMS_SOUTH
56. &QADAMS_TO_BRAINTREE
57. &BRAINTREE_SOUTH

58. &ALEWIFE_NORTH
59. &DAVIS_TO_ALEFWIFE
60. &DAVIS_NORTH
61. &PORTER_TO_DAVIS
62. &PORTER_NORTH
63. &HARVARD_TO_PORTER
64. &HARVARD_NORTH
65. &CENTRAL_TO_HARVARD
66. &CENTRAL_NORTH
67. &KENDALL_TO_CENTRAL
68. &KENDALL_NORTH
69. &CHARLES_TO_KENDALL
70. &CHARLES_NORTH
71. &PARKRED_TO_CHARLES
72. &PARKRED_NORTH
73. &DOWNTOWNRED_TO_PARKRED
74. &DOWNTOWNRED_NORTH
75. &SOUTH_TO_DOWNTOWNRED
76. &SOUTH_NORTH
77. &BROADWAY_TO_SOUTH_1
78. &BROADWAY_TO_SOUTH_2
79. &BROADWAY_NORTH
80. &ANDREW_TO_BROADWAY
81. &ANDREW_NORTH
82. &JFK_TO_ANDREW
83. &JFK_NORTH
84. &SAVIN_TO_JFK
85. &SAVIN_NORTH
86. &FIELDS_TO_SAVIN
87. &FIELDS_NORTH
88. &SHAWMUT_TO_FIELDS
89. &SHAWMUT_NORTH
90. &ASHMONT_TO_SHAWMUT
91. &ASHMONT_NORTH
92. &CEDAR_GROVE_TO_ASHMONT
93. &CEDAR_GROVE_NORTH
94. &BUTLER_TO_CEDAR_GROVE
95. &BUTLER_NORTH
96. &MILTON_TO_BUTLER
97. &MILTON_NORTH
98. &CENTRALST_TO_MILTON
99. &CENTRALST_NORTH
100. &VALLEY_TO_CENTRAL
101. &VALLEY_NORTH
102. &CAPEN_TO_VALLEY
103. &CAPEN_NORTH
104. &MATTAPAN_TO_CAPEN
105. &MATTAPAN_NORTH
106. &NQUINCY_TO_JFK
107. &NQUINCY_NORTH
108. &WOLLASTON_TO_NQUINCY
109. &WOLLASTON_NORTH
110. &QUINCYC_TO_WOLLASTON
111. &QUINCYC_NORTH
112. &QADAMS_TO_QUINCYC
113. &QADAMS_NORTH
114. &BRAINTREE_TO_QADAMS
115. &BRAINTREE_NORTH

 */